# Site settings
title: 
subtitle: "Abdul Hafeez | Postdoc, ME, GT, Atlanta, USA"
email: ahafeez@me.gatech.edu
description: "Computer Scientist - Accelerating collaboration at the intersection of materials science and data sceince"
baseurl: ""
url: "http://ahafeez.net"
twitter_username: "hokiekhan"
github_username:  "ahafeez7"
instagram_username: "xxx"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
